<a href="https://www.kaggle.com/code/tusharaggarwal27/decision-tree-practice?scriptVersionId=112572304" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

**Decision_Tree**

Tasks:
1. Please run a logistic regression model for social adv data
2. Build a DT model for diabetes data
3. Build a DT model for social adv data by including "Gender" as an input variable (x var) along with the other two x vars


In [262]:
# Data manipulation imports
import numpy as np
import pandas as pd

# Visualization imports
import matplotlib.pyplot as plt
import plotly.express as px

# Modeling imports
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay

**Case:- 3) Build a DT model for social adv data by including "Gender" as an input variable (x var) along with the other two x vars.**

In [263]:
#Loading the required data

social_data = pd.read_csv('/kaggle/input/social-network/Social_Network_Ads.csv')

In [264]:
#Checking the loaded data
social_data.head()
#pd.set_option('display.max_columns', None)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

**Basics Checks**

In [265]:
#Checking for all columns names
social_data.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [266]:
#Checking for shape of dataset
social_data.shape, print(social_data.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None


((400, 5), None)

In [267]:
#Cheking statistics
social_data.describe(include="all") 

User ID  Gender         Age  EstimatedSalary   Purchased
count   4.000000e+02     400  400.000000       400.000000  400.000000
unique           NaN       2         NaN              NaN         NaN
top              NaN  Female         NaN              NaN         NaN
freq             NaN     204         NaN              NaN         NaN
mean    1.569154e+07     NaN   37.655000     69742.500000    0.357500
std     7.165832e+04     NaN   10.482877     34096.960282    0.479864
min     1.556669e+07     NaN   18.000000     15000.000000    0.000000
25%     1.562676e+07     NaN   29.750000     43000.000000    0.000000
50%     1.569434e+07     NaN   37.000000     70000.000000    0.000000
75%     1.575036e+07     NaN   46.000000     88000.000000    1.000000
max     1.581524e+07     NaN   60.000000    150000.000000    1.000000

In [268]:
#convert categorical data('Gender') to binary data('0 & 1')
social_data_1 = pd.get_dummies(social_data["Gender"])
social_data_1


Female  Male
0         0     1
1         0     1
2         1     0
3         1     0
4         0     1
..      ...   ...
395       1     0
396       0     1
397       1     0
398       0     1
399       1     0

[400 rows x 2 columns]

In [269]:
#Using pd.get_dummies
social_data_converted = pd.concat((social_data, social_data_1), axis=1)
social_data_converted = social_data_converted.drop(['Gender'], axis=1)
social_data_converted = social_data_converted.drop(['Female'], axis=1)

social_data_converted

User ID  Age  EstimatedSalary  Purchased  Male
0    15624510   19            19000          0     1
1    15810944   35            20000          0     1
2    15668575   26            43000          0     0
3    15603246   27            57000          0     0
4    15804002   19            76000          0     1
..        ...  ...              ...        ...   ...
395  15691863   46            41000          1     0
396  15706071   51            23000          1     1
397  15654296   50            20000          1     0
398  15755018   36            33000          0     1
399  15594041   49            36000          1     0

[400 rows x 5 columns]

In [270]:
#Seprating for features and target variable
X = social_data_converted[['Age','EstimatedSalary','Male']].values
y = social_data_converted[['Purchased']].values

In [271]:
#Checking for columns
#print(X), print(y)

In [272]:
#Splitting train and test sets

X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size=0.30,random_state=123)

In [273]:
#Checking X_train, X_test, y_train, y_test shapes
print(X_train.shape), print(X_test.shape), print(y_train.shape), print(y_test.shape)

(280, 3)
(120, 3)
(280, 1)
(120, 1)


(None, None, None, None)

**Feature Scaling**

In [274]:
sc = StandardScaler() # creating the instance

In [275]:
#Standardizing the features
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [276]:
#Checking X_train, X_test
print(X_train), print(X_test)

[[-1.18758192e+00 -1.41222212e+00  1.02166316e+00]
 [-1.56869704e+00  9.15130245e-02  1.02166316e+00]
 [-9.97024365e-01 -3.29532816e-01  1.02166316e+00]
 [ 3.36878540e-01  3.02035945e-01  1.02166316e+00]
 [ 1.19438755e+00 -9.91176280e-01 -9.78796178e-01]
 [ 1.00382999e+00 -1.20169920e+00 -9.78796178e-01]
 [-6.15909250e-01 -1.53252093e+00  1.02166316e+00]
 [-9.01745587e-01  5.42633568e-01 -9.78796178e-01]
 [ 1.57550267e+00  3.13636187e-02  1.02166316e+00]
 [-9.01745587e-01 -4.19756925e-01 -9.78796178e-01]
 [-7.11188029e-01  3.02035945e-01 -9.78796178e-01]
 [ 1.57550267e+00 -1.29192331e+00 -9.78796178e-01]
 [-1.28286070e+00 -1.26184861e+00 -9.78796178e-01]
 [-8.06466808e-01  4.22334756e-01 -9.78796178e-01]
 [ 1.46320982e-01  1.11405292e+00  1.02166316e+00]
 [ 1.09910877e+00 -9.00952171e-01 -9.78796178e-01]
 [-2.34794134e-01 -1.26184861e+00  1.02166316e+00]
 [-7.11188029e-01 -1.56259563e+00  1.02166316e+00]
 [-5.20630471e-01 -1.53252093e+00  1.02166316e+00]
 [-2.34794134e-01 -1.38214742e+

(None, None)

In [277]:
#Importing the model DecisionTreeClassifier as target will be binary

from sklearn.tree import DecisionTreeClassifier

**Building the DT Model using the Training data**

**Here we create a DT classifier object.**

In [278]:
#Creting the insatance
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 123)

In [279]:
#Fitting the model on trainig data
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=123)

In [280]:
#Predicting on "Test Data"
y_pred = classifier.predict(X_test)
print(y_pred)

[1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 0
 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0
 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 1 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0
 0 1 0 1 0 0 0 1 0]


In [281]:
#Checking for 
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]]


In [282]:
#Getting the confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[69  8]
 [10 33]]


0.85

**Classification_report for Build a DT model for social adv data by including "Gender" as an input variable (x var) along with the other two x vars**

In [283]:
#printing Classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.90      0.88        77
           1       0.80      0.77      0.79        43

    accuracy                           0.85       120
   macro avg       0.84      0.83      0.84       120
weighted avg       0.85      0.85      0.85       120



=================================================================================

**Case:- 2) Build a DT model for diabetes data**

In [284]:
diab_data = pd.read_csv('/kaggle/input/diabetes/diabetes.csv')

In [285]:
diab_data

pregnant  glucose  pressure  triceps  insulin  mass  pedigree  age  \
0           1       89        66       23       94  28.1     0.167   21   
1           0      137        40       35      168  43.1     2.288   33   
2           3       78        50       32       88  31.0     0.248   26   
3           2      197        70       45      543  30.5     0.158   53   
4           1      189        60       23      846  30.1     0.398   59   
..        ...      ...       ...      ...      ...   ...       ...  ...   
387         0      181        88       44      510  43.3     0.222   26   
388         1      128        88       39      110  36.5     1.057   37   
389         2       88        58       26       16  28.4     0.766   22   
390        10      101        76       48      180  32.9     0.171   63   
391         5      121        72       23      112  26.2     0.245   30   

    diabetes  
0        neg  
1        pos  
2        pos  
3        pos  
4        pos  
..       ...  
387      pos  
388      pos  
389      neg  
390      neg  
391      neg  

[392 rows x 9 columns]

In [286]:
#Checking info for the data
diab_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pregnant  392 non-null    int64  
 1   glucose   392 non-null    int64  
 2   pressure  392 non-null    int64  
 3   triceps   392 non-null    int64  
 4   insulin   392 non-null    int64  
 5   mass      392 non-null    float64
 6   pedigree  392 non-null    float64
 7   age       392 non-null    int64  
 8   diabetes  392 non-null    object 
dtypes: float64(2), int64(6), object(1)
memory usage: 27.7+ KB


In [287]:
#convert categorical data('diabetes') to binary data('0 & 1')
diab_data_1 = pd.get_dummies(diab_data["diabetes"])
diab_data_1

#Using pd.get_dummies
diab_data_converted = pd.concat((diab_data, diab_data_1), axis=1)
diab_data_converted = diab_data_converted.drop(['diabetes'], axis=1)
diab_data_converted = diab_data_converted.drop(['neg'], axis=1)

diab_data_converted


pregnant  glucose  pressure  triceps  insulin  mass  pedigree  age  pos
0           1       89        66       23       94  28.1     0.167   21    0
1           0      137        40       35      168  43.1     2.288   33    1
2           3       78        50       32       88  31.0     0.248   26    1
3           2      197        70       45      543  30.5     0.158   53    1
4           1      189        60       23      846  30.1     0.398   59    1
..        ...      ...       ...      ...      ...   ...       ...  ...  ...
387         0      181        88       44      510  43.3     0.222   26    1
388         1      128        88       39      110  36.5     1.057   37    1
389         2       88        58       26       16  28.4     0.766   22    0
390        10      101        76       48      180  32.9     0.171   63    0
391         5      121        72       23      112  26.2     0.245   30    0

[392 rows x 9 columns]

In [288]:
#Seprating for features and target variable

X = diab_data_converted[['pregnant','glucose','pressure','triceps','insulin','mass','pedigree','age']].values
y = diab_data_converted[['pos']].values

In [289]:
#Checking for columns
#print(X), print(y)

In [290]:
#Splitting train and test sets

X_train, X_test, y_train, y_test  = train_test_split(X,y, test_size=0.3,random_state=123)

In [291]:
#Checking X_train, X_test, y_train, y_test shapes
print(X_train.shape), print(X_test.shape), print(y_train.shape), print(y_test.shape)

(274, 8)
(118, 8)
(274, 1)
(118, 1)


(None, None, None, None)

In [292]:
sc = StandardScaler() # creating the instance

In [293]:
#Standardizing the features
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [294]:
#Checking X_train, X_test
print(X_train), print(X_test)

[[ 0.48296257  1.36679416  0.07870895 ... -1.02783029  0.13067412
   1.88082828]
 [ 1.69423711  0.33847331  0.24147313 ... -1.01428409 -0.22836244
   4.73593603]
 [ 2.29987438  0.40274336  1.055294   ... -0.68917529 -0.79377434
   1.02429596]
 ...
 [-1.03113061 -0.68984754  0.56700148 ...  0.15068912 -0.85596965
  -0.68876869]
 [ 2.90551165  0.94903881  1.38082235 ...  0.97700732  1.79015805
   0.73878518]
 [ 0.48296257  0.0813931   0.56700148 ... -0.51307469 -0.28773069
   0.83395544]]
[[-0.69547614 -0.85509619  0.94717369 -0.32991825  0.26385193  0.43314694
  -0.77714883  1.39090398]
 [-0.02003429  1.24285267  0.01513898  0.12594069  1.68736449  0.51601227
  -0.43053204  0.53496307]
 [ 1.3308494   0.51023561  0.32581722 -0.23874646 -0.16897283 -1.0584291
   0.51563813  2.2468449 ]
 [-0.35775522  0.77664182 -0.91689573  0.39945605 -0.16897283 -0.13033734
  -0.18696348 -0.53496307]
 [ 2.34401217 -0.65529153  0.48115634  1.76703287  0.26385193  0.08511253
  -0.97075461  3.53075627]
 [ 0

(None, None)

**Building the DT Model using the Training data

Here we create a DT classifier object.**

In [295]:
#Creting the insatance
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 123)

In [296]:
#Fitting the model on trainig data
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=123)

In [297]:
#Predicting on "Test Data"
y_pred = classifier.predict(X_test)
print(y_pred)

[1 1 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 0 0 0
 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 0 0
 1 1 0 0 0 0 1]


In [298]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]]


In [299]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[67 17]
 [15 19]]


0.7288135593220338

In [300]:
#printing Classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81        84
           1       0.53      0.56      0.54        34

    accuracy                           0.73       118
   macro avg       0.67      0.68      0.68       118
weighted avg       0.73      0.73      0.73       118

